"""Content-free push delivery — MOBILE-COMPANION `MC-5` (S3 T3.2 + T3.3).

This is the module plan 42's ``push`` delivery target calls. It exists to solve exactly
one problem: **the phone is locked and a run is blocked on a permission decision.** A
push wakes the phone, the phone opens the companion route, and the *companion fetches
the details over the user's own link*. Nothing about the decision travels through a push
service.

## The payload contract — the security promise of this atom

A push payload is ``{"kind": ..., "item_id": ...}`` and NOTHING else. Not the tool name,
not its arguments, not a title, not a session key. Two independent reasons:

1. **A push service is a third party.** Web push goes through whichever endpoint the
   browser vendor assigned (FCM, Mozilla autopush, WNS); ntfy goes through whatever host
   the user configured. The soul guardrail for this plan is "no cloud middle tier holding
   state" — a payload carrying a tool's arguments would make every one of those hosts a
   holder of the thing the approval is about.
2. **Encrypted is not the same as absent.** RFC 8291 encryption means the push service
   cannot read the body, but it still stores and forwards it, its length is visible, and
   the ntfy path is not encrypted at all. Ids-only is the only claim that holds for both
   backends, so it is the only one made.

:func:`content_free_payload` is the ONE constructor and :func:`assert_content_free` is
the gate every sender passes through, so "ids only" is enforced at the call site that
builds the payload rather than trusted to each caller's discipline.

## Backends

``mobile.push_backend`` selects one:

* ``webpush`` — the browser's own W3C Push subscription, per device, encrypted per
  RFC 8291 and authorized per RFC 8292 (VAPID). Keys are generated by
  ``personalclaw push init`` and live in the credential store.
* ``ntfy`` — POST the same ids-only JSON to a user-configured ntfy topic URL
  (``mobile.ntfy_topic_url``). Fully self-hostable, no VAPID keys, no per-device
  subscription. The ntfy app renders the JSON verbatim, which is deliberately unpretty:
  the alternative is composing a sentence, and a sentence is content.
* ``relay`` — POST the same ids-only JSON, wrapped with a routing envelope
  (``{platform, token, payload}``), to a user-configured push-relay instance
  (``mobile.relay_url``) which forwards it to the vendor push services for the store app. The
  relay is
  stateless and open-source (deployable by anyone); the hosted instance is a
  convenience, never a dependency. Device tokens are registered per device id by the
  Capacitor shell, exactly as webpush subscriptions are by the browser.
* ``none`` — deliver nothing. Not an error, just off.

Delivery is **fail-open with respect to the notification it accompanies**: a push that
cannot be sent is logged and dropped, never raised, because a broken push transport must
not be able to suppress a dashboard notification (the same reason the rules layer in
``DashboardState.notify`` fails open).
"""

from __future__ import annotations

import base64
import json
import logging
import os
import threading
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

from personalclaw.atomic_write import atomic_write
from personalclaw.config import loader as config_loader
from personalclaw.config.credentials import OWNED_KEY_PREFIX


def config_dir() -> Path:
    """The active home, re-resolved per call — see :func:`personalclaw.config.loader.config_dir`.

    DEFINED here rather than imported: this module can be imported lazily, and an
    import-time binding captures whatever the name pointed at on first use (#2443).
    """
    return config_loader.config_dir()


logger = logging.getLogger(__name__)

#: Credential-store keys for the VAPID keypair. Core-OWNED keys (``PCSECRET_…``): the pair is
#: this install's own key material, not a secret the user manages, so Settings → Secrets does not
#: list it (deleting it there would silently stop every phone from ringing) and it is not mirrored
#: into the environment every child process inherits.
VAPID_PUBLIC_KEY = f"{OWNED_KEY_PREFIX}CORE_WEBPUSH__VAPID_PUBLIC"
VAPID_PRIVATE_KEY = f"{OWNED_KEY_PREFIX}CORE_WEBPUSH__VAPID_PRIVATE"

#: The names the pair had in ``credentials.json``, the store it lived in until this release, and
#: the keys ``llm.credentials.move_credentials_file`` moves them to.
MOVED_FROM_CREDENTIALS_FILE: dict[str, str] = {
    "PERSONALCLAW_VAPID_PUBLIC": VAPID_PUBLIC_KEY,
    "PERSONALCLAW_VAPID_PRIVATE": VAPID_PRIVATE_KEY,
}

#: The ONLY keys a push payload may carry. Asserted, not documented.
PAYLOAD_KEYS: frozenset[str] = frozenset({"kind", "item_id"})

#: Per-device W3C PushSubscription rows.
SUBSCRIPTIONS_FILE = "push_subscriptions.json"
FILE_MODE = 0o600

#: RFC 8292 ``sub`` claim. A push service uses it to contact the *sender* about abuse;
#: for a self-hosted gateway there is no such address, and inventing the user's real
#: email would leak an identifier to every push service. A non-routable mailto is the
#: honest answer and is what other self-hosted senders use.
VAPID_SUBJECT = "mailto:push@personalclaw.invalid"

#: VAPID JWT lifetime. Kept well under the 24h RFC 8292 maximum.
_JWT_TTL_SECS = 12 * 3600

#: Web-push record size. One record, so this is a formality — but it is a wire field and
#: a wrong value is rejected by the push service, so it is named rather than inlined.
_RECORD_SIZE = 4096

#: Outbound HTTP timeout. Short: a push is a wake-up ping, and a hung push service must
#: not hold a worker thread for minutes.
_HTTP_TIMEOUT_SECS = 10.0


class PushPayloadError(ValueError):
    """A payload carried something other than ``{kind, item_id}``.

    Raised, not logged-and-dropped: a leak is a defect in the caller, and silently
    stripping the extra key would let the defect ship.
    """


# ── The payload contract ────────────────────────────────────────────────────


def content_free_payload(kind: str, item_id: str) -> dict[str, str]:
    """The ids-only payload. **The one constructor** — never build this literal inline.

    Both values are coerced to ``str`` and stripped. ``item_id`` may be empty (a kind
    with no addressable item still tells the phone something arrived); ``kind`` may not,
    because the service worker maps it to the notification text.
    """
    k = str(kind or "").strip()
    if not k:
        raise PushPayloadError("push payload needs a kind")
    return {"kind": k, "item_id": str(item_id or "").strip()}


def assert_content_free(payload: Any) -> dict[str, str]:
    """Return *payload* iff it is exactly ``{kind, item_id}`` of strings.

    The gate every sender passes. Checks the key SET both ways — a missing key is as much
    a contract break as an extra one, because a sender that forgot ``item_id`` would ship
    a push the phone cannot route.
    """
    if not isinstance(payload, dict):
        raise PushPayloadError(f"push payload must be a dict, got {type(payload).__name__}")
    keys = set(payload)
    if keys != set(PAYLOAD_KEYS):
        extra = sorted(keys - PAYLOAD_KEYS)
        missing = sorted(PAYLOAD_KEYS - keys)
        raise PushPayloadError(
            "push payload must carry exactly {'kind', 'item_id'} — "
            f"extra={extra} missing={missing}. A push payload is CONTENT-FREE: the phone "
            "fetches the item over the user's own link."
        )
    for key in sorted(PAYLOAD_KEYS):
        if not isinstance(payload[key], str):
            raise PushPayloadError(
                f"push payload {key!r} must be a str, got {type(payload[key]).__name__}"
            )
    return dict(payload)


def payload_bytes(payload: dict[str, str]) -> bytes:
    """The wire form, gated. Compact and key-sorted so it is byte-stable across sends."""
    return json.dumps(assert_content_free(payload), separators=(",", ":"), sort_keys=True).encode()


# ── VAPID keypair ───────────────────────────────────────────────────────────


def _b64url(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def _b64url_decode(text: str) -> bytes:
    pad = "=" * (-len(text) % 4)
    return base64.urlsafe_b64decode(text + pad)


def push_init(*, force: bool = False) -> tuple[str, str]:
    """Generate the VAPID keypair and store it in the credential store.

    Returns ``(public_key, private_key)`` as base64url, the form both the browser
    (``applicationServerKey``) and the ``Authorization: vapid k=`` header want.

    Idempotent unless *force*: re-running returns the existing pair rather than minting a
    new one, because rotating the key **invalidates every existing subscription** — the
    browser bound its subscription to the old public key. ``--force`` exists for a real
    compromise and says so in the CLI help.
    """
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat

    existing = vapid_keys()
    if existing and not force:
        return existing

    private = ec.generate_private_key(ec.SECP256R1())
    private_raw = private.private_numbers().private_value.to_bytes(32, "big")
    public_raw = private.public_key().public_bytes(
        encoding=Encoding.X962, format=PublicFormat.UncompressedPoint
    )
    pub, priv = _b64url(public_raw), _b64url(private_raw)
    _store_vapid(pub, priv)
    return pub, priv


def _store_vapid(public_key: str, private_key: str) -> None:
    """Keep the pair in the credential store under :data:`VAPID_PUBLIC_KEY` and
    :data:`VAPID_PRIVATE_KEY`, both in one write."""
    from personalclaw.config.credentials import save_credentials

    save_credentials({VAPID_PUBLIC_KEY: public_key, VAPID_PRIVATE_KEY: private_key})


def vapid_keys() -> tuple[str, str] | None:
    """The stored ``(public, private)`` VAPID pair, or None when uninitialised."""
    try:
        from personalclaw.config.credentials import get_credential

        pub = get_credential(VAPID_PUBLIC_KEY)
        priv = get_credential(VAPID_PRIVATE_KEY)
    except Exception:
        logger.debug("VAPID key read failed", exc_info=True)
        return None
    if not pub or not priv:
        return None
    return pub, priv


def vapid_public_key() -> str:
    """The public key the browser needs, or "" when ``push init`` has not run."""
    keys = vapid_keys()
    return keys[0] if keys else ""


# ── Per-device subscriptions ────────────────────────────────────────────────


def subscriptions_path() -> Path:
    return config_dir() / SUBSCRIPTIONS_FILE


def load_subscriptions() -> dict[str, dict[str, Any]]:
    """Every stored subscription, keyed by device id. ``{}`` when absent/unreadable."""
    path = subscriptions_path()
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        logger.warning("push_subscriptions.json unreadable — treating as empty")
        return {}
    if not isinstance(data, dict):
        return {}
    return {k: v for k, v in data.items() if isinstance(v, dict)}


def _save_subscriptions(rows: dict[str, dict[str, Any]]) -> None:
    path = subscriptions_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    atomic_write(path, json.dumps(rows, indent=2, sort_keys=True) + "\n")
    try:
        os.chmod(path, FILE_MODE)
    except OSError:
        logger.debug("could not tighten %s to 0600", path, exc_info=True)


def subscribe(device_id: str, subscription: dict[str, Any]) -> None:
    """Store one W3C ``PushSubscription`` JSON against *device_id*.

    Only the three fields a sender needs are kept (``endpoint`` + the two keys). A
    browser's ``toJSON()`` also carries ``expirationTime`` and whatever a future spec
    adds; storing the whole blob would persist fields we never read and cannot reason
    about. Re-subscribing the same device REPLACES its row — a browser re-subscribes with
    a new endpoint whenever the old one is invalidated, and keeping both would send every
    push twice.
    """
    endpoint = str(subscription.get("endpoint") or "").strip()
    if not endpoint:
        raise ValueError("push subscription needs an endpoint")
    parsed = urlparse(endpoint)
    if parsed.scheme != "https" or not parsed.netloc:
        # Not politeness: the endpoint is where an encrypted payload is POSTed, and a
        # plaintext scheme would hand the ciphertext-plus-headers to the network.
        raise ValueError("push subscription endpoint must be https")
    keys = subscription.get("keys")
    keys = keys if isinstance(keys, dict) else {}
    p256dh = str(keys.get("p256dh") or "").strip()
    auth = str(keys.get("auth") or "").strip()
    if not p256dh or not auth:
        raise ValueError("push subscription needs keys.p256dh and keys.auth")

    rows = load_subscriptions()
    rows[str(device_id)] = {
        "endpoint": endpoint,
        "keys": {"p256dh": p256dh, "auth": auth},
        "created_at": time.time(),
    }
    _save_subscriptions(rows)


def unsubscribe(device_id: str) -> bool:
    """Drop *device_id*'s subscription. True when one was removed."""
    rows = load_subscriptions()
    if str(device_id) not in rows:
        return False
    rows.pop(str(device_id))
    _save_subscriptions(rows)
    return True


# ── Relay device tokens (the ``relay`` backend's per-device half) ───────────

#: Platforms the relay can route to. The vocabulary is closed on purpose: the relay's
#: whole job is picking the Apple vs the Google push service, so an open-ended string would
#: just defer the error.
RELAY_PLATFORMS: tuple[str, ...] = ("ios", "android")

RELAY_TOKENS_FILE = "push_relay_tokens.json"


def relay_tokens_path() -> Path:
    return config_dir() / RELAY_TOKENS_FILE


def load_relay_tokens() -> dict[str, dict[str, Any]]:
    """Every registered relay token, keyed by device id. ``{}`` when absent/unreadable."""
    path = relay_tokens_path()
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        logger.warning("push: relay token store unreadable — treating as empty", exc_info=True)
        return {}
    return data if isinstance(data, dict) else {}


def _save_relay_tokens(rows: dict[str, dict[str, Any]]) -> None:
    path = relay_tokens_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".tmp")
    tmp.write_text(json.dumps(rows, indent=1), encoding="utf-8")
    tmp.replace(path)


def register_relay_token(device_id: str, platform: str, token: str) -> None:
    """Store one Apple/Google push-service device token against *device_id*.

    Mirrors :func:`subscribe`'s discipline: only the two fields a sender needs are kept,
    and re-registering the same device REPLACES its row (platforms rotate tokens, and
    keeping both would ping the phone twice).
    """
    platform = str(platform or "").strip().lower()
    if platform not in RELAY_PLATFORMS:
        raise ValueError(f"relay platform must be one of {RELAY_PLATFORMS}")
    token = str(token or "").strip()
    if not token:
        raise ValueError("relay registration needs a device token")

    rows = load_relay_tokens()
    rows[str(device_id)] = {"platform": platform, "token": token, "created_at": time.time()}
    _save_relay_tokens(rows)


def unregister_relay_token(device_id: str) -> bool:
    """Drop *device_id*'s relay token. True when one was removed."""
    rows = load_relay_tokens()
    if str(device_id) not in rows:
        return False
    rows.pop(str(device_id))
    _save_relay_tokens(rows)
    return True


# ── Web push (RFC 8291 encryption + RFC 8292 authorization) ─────────────────


def _hkdf(salt: bytes, ikm: bytes, info: bytes, length: int) -> bytes:
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.kdf.hkdf import HKDF

    return HKDF(algorithm=hashes.SHA256(), length=length, salt=salt, info=info).derive(ikm)


def encrypt_payload(plaintext: bytes, p256dh: str, auth: str, *, salt: bytes = b"") -> bytes:
    """RFC 8291 ``aes128gcm`` body for *plaintext*.

    *salt* is a parameter only so a test can pin the whole body byte-for-byte against the
    RFC's vectors; production always passes nothing and gets 16 fresh random bytes.
    """
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat

    ua_public_raw = _b64url_decode(p256dh)
    auth_secret = _b64url_decode(auth)
    salt = salt or os.urandom(16)

    ua_public = ec.EllipticCurvePublicKey.from_encoded_point(ec.SECP256R1(), ua_public_raw)
    ephemeral = ec.generate_private_key(ec.SECP256R1())
    as_public_raw = ephemeral.public_key().public_bytes(
        encoding=Encoding.X962, format=PublicFormat.UncompressedPoint
    )
    shared = ephemeral.exchange(ec.ECDH(), ua_public)

    # §3.3: the key-derivation info binds BOTH public keys, so a shared secret cannot be
    # replayed against a different recipient.
    prk = _hkdf(
        salt=auth_secret,
        ikm=shared,
        info=b"WebPush: info\x00" + ua_public_raw + as_public_raw,
        length=32,
    )
    cek = _hkdf(salt=salt, ikm=prk, info=b"Content-Encoding: aes128gcm\x00", length=16)
    nonce = _hkdf(salt=salt, ikm=prk, info=b"Content-Encoding: nonce\x00", length=12)

    # 0x02 is the LAST-record delimiter (RFC 8188 §2). One record, so it is always last.
    ciphertext = AESGCM(cek).encrypt(nonce, plaintext + b"\x02", None)
    header = salt + _RECORD_SIZE.to_bytes(4, "big") + len(as_public_raw).to_bytes(1, "big")
    return header + as_public_raw + ciphertext


def vapid_header(endpoint: str, *, now: float | None = None) -> str:
    """The RFC 8292 ``Authorization: vapid t=…,k=…`` value for *endpoint*.

    The ``aud`` claim is the endpoint's ORIGIN, not the full URL: a token scoped to the
    full path would still be accepted, but the RFC scopes it to the origin and some
    services check exactly that.
    """
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature

    keys = vapid_keys()
    if keys is None:
        raise RuntimeError("no VAPID keypair — run `personalclaw push init`")
    public_key, private_key = keys

    parsed = urlparse(endpoint)
    audience = f"{parsed.scheme}://{parsed.netloc}"
    issued = int(now if now is not None else time.time())
    header = _b64url(json.dumps({"typ": "JWT", "alg": "ES256"}, separators=(",", ":")).encode())
    claims = _b64url(
        json.dumps(
            {"aud": audience, "exp": issued + _JWT_TTL_SECS, "sub": VAPID_SUBJECT},
            separators=(",", ":"),
        ).encode()
    )
    signing_input = f"{header}.{claims}".encode()

    private = ec.derive_private_key(
        int.from_bytes(_b64url_decode(private_key), "big"), ec.SECP256R1()
    )
    der = private.sign(signing_input, ec.ECDSA(hashes.SHA256()))
    r, s = decode_dss_signature(der)
    # ES256 wants the raw 64-byte r||s pair, NOT the DER structure `sign()` returns. A DER
    # signature here is accepted by nothing and fails as a 401 with no useful message.
    signature = _b64url(r.to_bytes(32, "big") + s.to_bytes(32, "big"))
    return f"vapid t={header}.{claims}.{signature},k={public_key}"


def _post(url: str, body: bytes, headers: dict[str, str]) -> int:
    request = urllib.request.Request(url, data=body, headers=headers, method="POST")
    with urllib.request.urlopen(request, timeout=_HTTP_TIMEOUT_SECS) as response:  # noqa: S310
        return int(response.status)


def send_webpush(device_id: str, payload: dict[str, str]) -> bool:
    """Encrypt and POST *payload* to *device_id*'s subscription. True when accepted.

    A ``404``/``410`` means the browser threw the subscription away, so the row is
    dropped here rather than left to fail forever — a dead endpoint retried on every
    notification is how a push transport turns into a log-spam generator.
    """
    row = load_subscriptions().get(str(device_id))
    if row is None:
        logger.debug("push: no subscription for device %s", device_id)
        return False
    body = payload_bytes(payload)
    try:
        encrypted = encrypt_payload(body, row["keys"]["p256dh"], row["keys"]["auth"])
        headers = {
            "Authorization": vapid_header(row["endpoint"]),
            "Content-Encoding": "aes128gcm",
            "Content-Type": "application/octet-stream",
            "Content-Length": str(len(encrypted)),
            "TTL": "60",
            # An approval is the definition of time-critical, and `high` is what keeps a
            # locked phone from batching the wake-up into its next maintenance window.
            "Urgency": "high",
        }
        status = _post(row["endpoint"], encrypted, headers)
    except urllib.error.HTTPError as exc:
        if exc.code in (404, 410):
            unsubscribe(device_id)
            logger.info("push: endpoint gone for device %s — subscription dropped", device_id)
        else:
            logger.warning("push: %s rejected the ping (%s)", device_id, exc.code)
        return False
    except Exception:
        logger.warning("push: send failed for device %s", device_id, exc_info=True)
        return False
    return 200 <= status < 300


def send_ntfy(payload: dict[str, str], topic_url: str) -> bool:
    """POST the ids-only JSON to a user-configured ntfy topic URL.

    Body ONLY — no ``Title``, no ``Tags``, no ``Click``. Every ntfy header is rendered to
    the user by the ntfy app, and anything worth putting there would be composed from the
    item, i.e. content. The tradeoff is that ntfy shows raw JSON; that is the honest cost
    of the ids-only promise and it is documented in the remote-access guide.

    Refuses a non-https destination. ``config/loader.py`` deliberately keeps the URL
    verbatim (so the settings field shows what the user typed and the PATCH can explain a
    rejection), which makes THIS the fail-closed point: a ping published over plain http
    would put the item id on the wire in the clear.
    """
    if urlparse(topic_url).scheme != "https":
        logger.warning("push: refusing to publish to a non-https ntfy topic URL")
        return False
    body = payload_bytes(payload)
    try:
        status = _post(
            topic_url,
            body,
            {"Content-Type": "application/json", "Content-Length": str(len(body))},
        )
    except Exception:
        logger.warning("push: ntfy publish failed", exc_info=True)
        return False
    return 200 <= status < 300


def send_relay(payload: dict[str, str], relay_url: str, platform: str, token: str) -> bool:
    """POST one ids-only ping to the configured relay, wrapped in a routing envelope.

    The body is built from exactly four things — the platform, the device token, and the
    two payload ids — so the relay physically cannot receive content. The token is a
    routing address for the relay, not a secret to us, but it IS a capability against
    the vendor push service, so it never reaches a log line (mirroring the webpush
    endpoint discipline).

    Refuses a non-https destination, exactly like :func:`send_ntfy` and for the same
    reason: config keeps the URL verbatim so the settings PATCH can explain a rejection,
    which makes THIS the fail-closed point.
    """
    if urlparse(relay_url).scheme != "https":
        logger.warning("push: refusing to publish to a non-https relay URL")
        return False
    body = json.dumps(
        {"platform": platform, "token": token, "payload": assert_content_free(payload)}
    ).encode("utf-8")
    try:
        status = _post(
            relay_url,
            body,
            {"Content-Type": "application/json", "Content-Length": str(len(body))},
        )
    except Exception:
        logger.warning("push: relay publish failed", exc_info=True)
        return False
    return 200 <= status < 300


# ── The plan-42 `push` target ───────────────────────────────────────────────


def push_backend() -> str:
    """The configured backend, defaulting to ``webpush`` on any read failure.

    Fails to the configured DEFAULT rather than to ``none``: a config read that broke
    should not silently turn off the transport a user is relying on for approvals.
    """
    try:
        from personalclaw.config.loader import AppConfig

        return (AppConfig.load().mobile.push_backend or "webpush").strip().lower()
    except Exception:
        logger.debug("push backend read failed — assuming webpush", exc_info=True)
        return "webpush"


def ntfy_topic_url() -> str:
    try:
        from personalclaw.config.loader import AppConfig

        return (AppConfig.load().mobile.ntfy_topic_url or "").strip()
    except Exception:
        logger.debug("ntfy topic url read failed", exc_info=True)
        return ""


def relay_url() -> str:
    try:
        from personalclaw.config.loader import AppConfig

        return (AppConfig.load().mobile.relay_url or "").strip()
    except Exception:
        logger.debug("relay url read failed", exc_info=True)
        return ""


def send_push(device_id: str, payload: dict[str, Any]) -> bool:
    """Plan C3's per-device sender. Gated on the payload contract before anything else."""
    return send_webpush(device_id, assert_content_free(payload))


def deliver(kind: str, item_id: str) -> int:
    """Send one content-free ping for ``(kind, item_id)``. Returns the number delivered.

    **This is plan 42's ``push`` target.** The rules engine decides WHETHER to call it
    (``push`` in the resolved rule's targets); this function only decides HOW, from
    ``mobile.push_backend``. Never raises — see the module docstring on fail-open.
    """
    payload = content_free_payload(kind, item_id)
    backend = push_backend()
    if backend == "none":
        return 0
    if backend == "ntfy":
        url = ntfy_topic_url()
        if not url:
            logger.debug("push: backend is ntfy but mobile.ntfy_topic_url is empty")
            return 0
        delivered = 1 if send_ntfy(payload, url) else 0
    elif backend == "relay":
        url = relay_url()
        if not url:
            logger.debug("push: backend is relay but mobile.relay_url is empty")
            return 0
        delivered = sum(
            1
            for row in load_relay_tokens().values()
            if send_relay(payload, url, str(row.get("platform", "")), str(row.get("token", "")))
        )
    elif backend == "webpush":
        delivered = sum(1 for device in list(load_subscriptions()) if send_webpush(device, payload))
    else:
        logger.warning("push: unknown backend %r — nothing sent", backend)
        return 0
    if delivered:
        _audit(payload, backend, delivered)
    return delivered


def _audit(payload: dict[str, str], backend: str, delivered: int) -> None:
    """SEL line for a delivered ping. Carries the same ids the payload does, and no more."""
    try:
        from personalclaw.sel import sel

        sel().log_api_access(
            caller="push",
            operation=f"push_sent:{backend}",
            outcome="success",
            resources=f"kind={payload['kind']} item_id={payload['item_id']} devices={delivered}",
        )
    except Exception:
        logger.debug("SEL audit failed for push send", exc_info=True)


def deliver_async(kind: str, item_id: str) -> None:
    """:func:`deliver` on a daemon thread.

    Every call site is a notification chokepoint (``DashboardState.notify``,
    ``request_approval``) running on the gateway's event loop, and delivery is a
    blocking HTTPS POST per device to a third-party host. Doing it inline would make a
    slow push service delay the dashboard broadcast — i.e. the desktop notification would
    wait on the phone's. A daemon thread so process exit is never held up by a ping.
    """
    try:
        threading.Thread(
            target=deliver, args=(kind, item_id), name="push-deliver", daemon=True
        ).start()
    except Exception:
        logger.debug("push: could not start delivery thread", exc_info=True)


def push_cmd(args: Any) -> int:
    """``personalclaw push {init,status,test}`` — the CLI half of MC-5.

    ``init`` is the command the criterion names: it mints the VAPID keypair into the
    credential store. ``test`` exists because the last leg of this atom's validation (a
    locked phone on cell data, timed) can only be driven by a human holding the phone — so
    the tool that drives it ships with the feature instead of being improvised later.
    """
    action = getattr(args, "push_command", "") or "status"

    if action == "init":
        force = bool(getattr(args, "force", False))
        had = vapid_keys() is not None
        public_key, _ = push_init(force=force)
        if had and not force:
            print("VAPID keypair already present (use --force to rotate).")
        elif had:
            print("VAPID keypair ROTATED — every existing subscription is now invalid.")
            print("Re-subscribe each device from Settings → Companion apps.")
        else:
            print("VAPID keypair generated and stored in the credential store.")
        print(f"\nPublic key: {public_key}")
        return 0

    if action == "test":
        kind = str(getattr(args, "kind", "") or "approval")
        item_id = str(getattr(args, "item_id", "") or "test")
        sent = deliver(kind, item_id)
        payload = content_free_payload(kind, item_id)
        print(f"backend={push_backend()} delivered={sent} payload={json.dumps(payload)}")
        if not sent:
            print("Nothing was delivered — check `personalclaw push status`.")
            return 1
        return 0

    status = push_status()
    print(f"backend:        {status['backend']}")
    print(f"VAPID keypair:  {'present' if status['vapid_ready'] else 'MISSING (run push init)'}")
    print(f"ntfy topic:     {'configured' if status['ntfy_configured'] else 'not configured'}")
    print(f"subscribed:     {status['subscribed']} device(s)")
    for device in status["devices"]:
        print(f"  - {device}")
    return 0


def approval_targeted() -> bool:
    """True when plan 42's rule for ``approval/requested`` routes to the ``push`` target.

    Surfaced because the transport and the routing are two separate decisions, and a device
    that is subscribed while approvals are NOT routed to it is silent for a reason the user
    cannot otherwise see. Naming it is the alternative to a hidden second switch.
    """
    try:
        from personalclaw import notification_rules

        rule = notification_rules.resolve_rule("approval", "requested")
        return rule.mode != "never" and "push" in rule.targets
    except Exception:
        logger.debug("approval rule read failed", exc_info=True)
        return False


def push_status() -> dict[str, Any]:
    """What the settings surface and the phone need to know. Never includes a secret."""
    backend = push_backend()
    subs = load_subscriptions()
    return {
        "backend": backend,
        "vapid_public_key": vapid_public_key() if backend == "webpush" else "",
        "vapid_ready": vapid_keys() is not None,
        "ntfy_configured": bool(ntfy_topic_url()),
        "relay_configured": bool(relay_url()),
        "relay_devices": sorted(load_relay_tokens()),
        "approval_targeted": approval_targeted(),
        "devices": sorted(subs),
        "subscribed": len(subs),
    }
